export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const SUCCESS_USER_REQUEST = 'SUCCESS_USER_REQUEST';
export const ERROR_USER_REQUEST = 'ERROR_USER_REQUEST';
export const USER_CONFIRM_REQUEST = 'USER_CONFIRM_REQUEST';
export const USER_CONFIRM_SUCCESS = 'USER_CONFIRM_SUCCESS';
export const USER_CONFIRM_FAILED = 'USER_CONFIRM_FAILED';

export const INVOKE_USER_EXISTS_REQUEST = 'INVOKE_USER_EXISTS_REQUEST';
export const USER_EXISTS_REQUEST = 'USER_EXISTS_REQUEST';
export const ERROR_USER_EXISTS_REQUEST = 'ERROR_USER_EXISTS_REQUEST';

/* flash message event constants */
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_ALL_FLASH_MESSAGES = 'DELETE_ALL_FLASH_MESSAGES';

/* log in event constants */
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

/* forgot password event constants */
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const VALIDATE_TOKEN_REQUEST = 'VALIDATE_TOKEN_REQUEST';
export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS';
export const VALIDATE_TOKEN_ERROR = 'VALIDATE_TOKEN_ERROR';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

/* chat event constants */
export const ADD_USER = 'ADD_USER';
export const UPDATE_USERS_LIST = 'UPDATE_USERS_LIST';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';

/* soket event constants */
export const INIT_SOCKET_CONNECTION = 'INIT_SOCKET_CONNECTION';
export const DISCONNECT_SOCKET_CONNECTION = 'DISCONNECT_SOCKET_CONNECTION';